// <auto-generated />
using System;
using ElectricalProspectingProfiling.Database.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricalProspectingProfiling.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("ГеологическиеДанныеID")
                        .HasColumnType("int");

                    b.Property<int>("КлиентID")
                        .HasColumnType("int");

                    b.Property<DateTime>("КонецДата")
                        .HasColumnType("datetime2");

                    b.Property<string>("Контакты")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("НачалоДата")
                        .HasColumnType("datetime2");

                    b.Property<int>("ПлощадьID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ГеологическиеДанныеID");

                    b.HasIndex("ПлощадьID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.CoordinatsProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SquareID")
                        .HasColumnType("int");

                    b.Property<decimal>("XКоордината")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YКоордината")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("SquareID");

                    b.ToTable("CoordinatsProfile");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.CoordinatsSquare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SquareID")
                        .HasColumnType("int");

                    b.Property<decimal>("XКоордината")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YКоордината")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("SquareID");

                    b.ToTable("CoordinatsSquare");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Контакты")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Geodesist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Контакты")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Geodesist");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.GeologicalData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ГеодезистID")
                        .HasColumnType("int");

                    b.Property<string>("Загрязнение")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ИзмеренияID")
                        .HasColumnType("int");

                    b.Property<string>("ОписаниеСтруктуры")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ТипПороды")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ГеодезистID");

                    b.HasIndex("ИзмеренияID");

                    b.ToTable("GeologicalData");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Measurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Вольтаж")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Дата")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ДистанцияМеждуЭлектродами")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ПикетID")
                        .HasColumnType("int");

                    b.Property<decimal>("Сопротивление")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Температура")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ТипПрофилирования")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ток")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ПикетID");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Picket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Дистанция")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Координаты")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Номер")
                        .HasColumnType("int");

                    b.Property<int>("ПрофильID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ПрофильID");

                    b.ToTable("Picket");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Profile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("КоординатыID")
                        .HasColumnType("int");

                    b.Property<string>("МетодПрофилирования")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ПлощадьID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("КоординатыID");

                    b.HasIndex("ПлощадьID");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Square", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Высота")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("КоординатыID")
                        .HasColumnType("int");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Squares");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Contract", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricalProspectingProfiling.Model.GeologicalData", "GeologicalData")
                        .WithMany()
                        .HasForeignKey("ГеологическиеДанныеID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricalProspectingProfiling.Model.Square", "Square")
                        .WithMany()
                        .HasForeignKey("ПлощадьID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("GeologicalData");

                    b.Navigation("Square");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.CoordinatsProfile", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Square", "Square")
                        .WithMany()
                        .HasForeignKey("SquareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Square");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.CoordinatsSquare", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Square", "Square")
                        .WithMany("CoordinatsSquares")
                        .HasForeignKey("SquareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Square");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.GeologicalData", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Geodesist", "Geodesist")
                        .WithMany()
                        .HasForeignKey("ГеодезистID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricalProspectingProfiling.Model.Measurement", "Measurement")
                        .WithMany("GeologicalDataList")
                        .HasForeignKey("ИзмеренияID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geodesist");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Measurement", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Picket", "Picket")
                        .WithMany("Measurements")
                        .HasForeignKey("ПикетID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picket");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Picket", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.Profile", "Profile")
                        .WithMany("Pickets")
                        .HasForeignKey("ПрофильID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Profile", b =>
                {
                    b.HasOne("ElectricalProspectingProfiling.Model.CoordinatsProfile", "CoordinatsProfile")
                        .WithMany()
                        .HasForeignKey("КоординатыID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectricalProspectingProfiling.Model.Square", "Square")
                        .WithMany()
                        .HasForeignKey("ПлощадьID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoordinatsProfile");

                    b.Navigation("Square");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Measurement", b =>
                {
                    b.Navigation("GeologicalDataList");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Picket", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Profile", b =>
                {
                    b.Navigation("Pickets");
                });

            modelBuilder.Entity("ElectricalProspectingProfiling.Model.Square", b =>
                {
                    b.Navigation("CoordinatsSquares");
                });
#pragma warning restore 612, 618
        }
    }
}
